### PR TITLE
Fuse ESB Role Development, basic installation of FUSE

### PR DESCRIPTION
**Pull request by kameshsampath**
- Basic role setup in line with other middleware roles
- has travis ci integration for syntax check alone

### CODE REVIEW

**Comment by sabre1041** [comment]
LGTM. I do not have access to merge this. @sherl0cks do you?

**Comment by itewk** [comment]
@sabre1041 let me know if you all need access, I have the power.

**Comment by sabre1041** [comment]
@itewk i do. can i get some good karma my way?

**Comment by sabre1041** [comment]
@itewk, @sherl0cks gave me the power. thanks for the offer!

**Pull request merged**
