### PR TITLE
#14 - Fix links to example playbooks

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
the build failure is completely unrelated:

"The command "sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine" failed and exited with 100 during ."

EDIT: there was the same error for another PR job: https://travis-ci.org/redhat-cop/jboss_fuse/builds/372566819

**Comment by sabre1041** [comment]
@apupier Thanks for the contribution. I made some changes over the weekend and as you can see, we are now getting passing builds. Can you take a look at the README.md and update the organization to `redhat-cop`? Then we should be good to merge in the changes.

**Comment by apupier** [comment]
> @apupier Thanks for the contribution. I made some changes over the weekend and as you can see, we are now getting passing builds.

thanks

> Can you take a look at the README.md and update the organization to redhat-cop? Then we should be good to merge in the changes.

done

**Comment by apupier** [comment]
@sabre1041 ping to be sure that you noticed that i updated the PR :-)

**Pull request merged**
